server:
  port: 8080

spring:
  application:
    name: message-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

auth-server: http://@auth-service-host@:18080/uaa

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka-service-host@:8761/eureka

