server:
  port: 9999
  use-forward-headers: true

spring:
  application:
    name: zuul

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  routes:
    authorization:
      path: /uaa/**
      service-id: authorization
      sensitiveHeaders:
      strip-prefix: false
    message-service:
      path: /api/v1/messages/**
      service-id: message-service
      sensitiveHeaders:
      url: http://localhost:8080/
      strip-prefix: false
    user-service:
      path: /api/v1/users/**
      service-id: user-service
      sensitiveHeaders:
      url: http://localhost:8081/
      strip-prefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

application:
  filter:
    prefix: /api/v1/users
    suffix: /my
    method: GET

#zuul:
#  host:
#    socket-timeout-millis: 60000
#  add-host-header: true
#  add-proxy-headers: true
#  routes:
#    authorization:
#      path: /uaa/**
#      service-id: authorization
#      sensitiveHeaders:
#      strip-prefix: false
#      url: http://authorization:18080/
#    client:
#      path: /api/v1/messages/**
#      service-id: message-service
#      sensitiveHeaders:
#      url: http://message-service:8080/
#      strip-prefix: false
#    user-service:
#      path: /api/v1/users/**
#      service-id: user-service
#      sensitiveHeaders:
#      url: http://user-service:8081/
#      strip-prefix: false
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
