server:
  port: 9999
  use-forward-headers: true
spring.application.name: zuul

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  routes:
    uaa:
      path: /uaa/**
      service-id: uaa
      sensitiveHeaders:
      strip-prefix: false
    client:
      path: /message-service/**
      service-id: message-service
      sensitiveHeaders:
      strip-prefix: false
    user-service:
      path: /user-service/**
      service-id: user-service
      sensitiveHeaders:
#      strip-prefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
