server:
  port: 9999
  use-forward-headers: true
spring.application.name: zuul

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  routes:
    uaa:
      path: /uaa/**
      service-id: uaa
      sensitiveHeaders:
      strip-prefix: false
    client:
      path: /api/v1/messages/**
      service-id: message-service
      sensitiveHeaders:
      url: http://localhost:8080/
      strip-prefix: false
    user-service:
      path: /api/v1/users/**
      service-id: user-service
      sensitiveHeaders:
      url: http://localhost:18082/
      strip-prefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

application:
  filter:
    prefix: /api/v1/users
    suffix: /my
    method: GET
