server:
  port: 8081

spring:
  application:
    name: user-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

auth-server: http://localhost:9999/uaa
#auth-server: http://zuul:9999/uaa
#auth-server: http://authorization:18080/uaa

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
